import type { DurableMediaLibraryRecords } from "@/lib/media/media-durable-types";

const timestamp = "2026-05-23T00:00:00.000Z";
const accountId = "account-britton-local";

export const durableDemoMediaRecords: DurableMediaLibraryRecords = {
  accounts: [
    {
      id: accountId,
      displayName: "Britton",
      createdAt: timestamp,
      updatedAt: timestamp,
    },
  ],
  profiles: [
    {
      id: "britton",
      accountId,
      name: "Britton",
      sortOrder: 1,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: "friend",
      accountId,
      name: "Friend",
      sortOrder: 2,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: "guest",
      accountId,
      name: "Guest",
      sortOrder: 3,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
  ],
  sources: [
    {
      id: "source-they-were-right",
      accountId,
      sourceKind: "authorized-local-sample",
      sourcePath: "/media/they-were-right.mp4",
      sourceLabel: "Manual local MP4 catalog entry",
      localFileStrategy: "manual-public-media-match",
      expectedFileName: "they-were-right.mp4",
      rightsReminder:
        "Use only the local MP4 Britton owns, created, or has permission to test.",
      curationChecklist: [
        "Confirm /media/they-were-right.mp4 plays directly in the browser.",
        "Open /media and select They Were Right.",
        "Play, seek, and refresh to confirm Continue Watching persists.",
      ],
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: "source-survivors-of-saturn",
      accountId,
      sourceKind: "authorized-local-sample",
      sourcePath: "/media/survivors-of-saturn.mp4",
      sourceLabel: "Manual local MP4 catalog entry",
      localFileStrategy: "manual-public-media-match",
      expectedFileName: "survivors-of-saturn.mp4",
      rightsReminder:
        "Use only the local MP4 Britton owns, created, or has permission to test.",
      curationChecklist: [
        "Confirm /media/survivors-of-saturn.mp4 plays directly in the browser.",
        "Open /media and select Survivors of Saturn.",
        "Play, seek, and refresh to confirm Continue Watching persists.",
      ],
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: "source-kabbalah-intro",
      accountId,
      sourceKind: "authorized-local-sample",
      sourcePath: "/media/kabbalah-intro.mp4",
      sourceLabel: "Manual local MP4 catalog entry",
      localFileStrategy: "manual-public-media-match",
      expectedFileName: "kabbalah-intro.mp4",
      rightsReminder:
        "Use only the local MP4 Britton owns, created, or has permission to test.",
      curationChecklist: [
        "Confirm /media/kabbalah-intro.mp4 plays directly in the browser.",
        "Open /media and select Kabbalah Intro.",
        "Play, seek, and refresh to confirm Continue Watching persists.",
      ],
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: "source-jesus-was-not-a-christian",
      accountId,
      sourceKind: "authorized-local-sample",
      sourcePath: "/media/jesus-was-not-a-christian.mp4",
      sourceLabel: "Manual local MP4 catalog entry",
      localFileStrategy: "manual-public-media-match",
      expectedFileName: "jesus-was-not-a-christian.mp4",
      rightsReminder:
        "Use only the local MP4 Britton owns, created, or has permission to test.",
      curationChecklist: [
        "Confirm /media/jesus-was-not-a-christian.mp4 plays directly in the browser.",
        "Open /media and select Jesus Was Not a Christian.",
        "Play, seek, and refresh to confirm Continue Watching persists.",
      ],
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: "source-local-lights",
      accountId,
      sourceKind: "authorized-local-sample",
      sourcePath: "/media/sample-movie.mp4",
      sourceLabel: "Authorized local MP4 sample",
      localFileStrategy: "manual-public-media-match",
      expectedFileName: "sample-movie.mp4",
      rightsReminder:
        "Use only an MP4 Britton owns, created, or has permission to test.",
      curationChecklist: [
        "Place the file at public/media/sample-movie.mp4.",
        "Open /media and select Local Lights.",
        "Confirm the source status changes to Ready after playback can load.",
      ],
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: "source-workbench-weekend",
      accountId,
      sourceKind: "authorized-local-sample",
      sourcePath: "/media/sample-workbench.webm",
      sourceLabel: "Authorized local WebM sample",
      localFileStrategy: "manual-public-media-match",
      expectedFileName: "sample-workbench.webm",
      rightsReminder:
        "Use only a WebM Britton owns, created, or has permission to test.",
      curationChecklist: [
        "Place the file at public/media/sample-workbench.webm.",
        "Open /media and select Workbench Weekend.",
        "Confirm missing state becomes Ready when the browser can load it.",
      ],
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: "source-signal-house-s1e1",
      accountId,
      sourceKind: "authorized-local-sample",
      sourcePath: "/media/sample-episode-1.mp4",
      sourceLabel: "Authorized local MP4 episode sample",
      localFileStrategy: "manual-public-media-match",
      expectedFileName: "sample-episode-1.mp4",
      rightsReminder:
        "Use only an episode sample Britton owns, created, or has permission to test.",
      curationChecklist: [
        "Place the file at public/media/sample-episode-1.mp4.",
        "Open /media and select Pilot Light.",
        "Seek and refresh to confirm progress persists.",
      ],
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: "source-signal-house-s1e2",
      accountId,
      sourceKind: "authorized-local-sample",
      sourcePath: "/media/sample-episode-2.mp4",
      sourceLabel: "Authorized local MP4 episode sample",
      localFileStrategy: "manual-public-media-match",
      expectedFileName: "sample-episode-2.mp4",
      rightsReminder:
        "Use only an episode sample Britton owns, created, or has permission to test.",
      curationChecklist: [
        "Place the file at public/media/sample-episode-2.mp4.",
        "Open /media and select Second Signal.",
        "Confirm Watchlist and progress remain profile-specific.",
      ],
      createdAt: timestamp,
      updatedAt: timestamp,
    },
  ],
  catalogItems: [
    {
      id: "movie-they-were-right",
      accountId,
      mediaSourceId: "source-they-were-right",
      type: "movie",
      title: "They Were Right",
      description:
        "A locally supplied MP4 served directly from public/media and listed through the manual media catalog.",
      runtimeMinutes: 60,
      posterPath: "/media/poster-they-were-right.jpg",
      releaseYear: 2026,
      rating: "Unrated",
      libraryStatus: "ready-for-owned-file",
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: "movie-survivors-of-saturn",
      accountId,
      mediaSourceId: "source-survivors-of-saturn",
      type: "movie",
      title: "Survivors of Saturn",
      description:
        "A locally supplied MP4 served directly from public/media and listed through the manual media catalog.",
      runtimeMinutes: 60,
      posterPath: "/media/poster-survivors-of-saturn.jpg",
      releaseYear: 2026,
      rating: "Unrated",
      libraryStatus: "ready-for-owned-file",
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: "movie-kabbalah-intro",
      accountId,
      mediaSourceId: "source-kabbalah-intro",
      type: "movie",
      title: "Kabbalah Intro",
      description:
        "A locally supplied MP4 served directly from public/media and listed through the manual media catalog.",
      runtimeMinutes: 60,
      posterPath: "/media/poster-kabbalah-intro.jpg",
      releaseYear: 2026,
      rating: "Unrated",
      libraryStatus: "ready-for-owned-file",
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: "movie-jesus-was-not-a-christian",
      accountId,
      mediaSourceId: "source-jesus-was-not-a-christian",
      type: "movie",
      title: "Jesus Was Not a Christian",
      description:
        "A locally supplied MP4 served directly from public/media and listed through the manual media catalog.",
      runtimeMinutes: 60,
      posterPath: "/media/poster-jesus-was-not-a-christian.jpg",
      releaseYear: 2026,
      rating: "Unrated",
      libraryStatus: "ready-for-owned-file",
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: "movie-local-lights",
      accountId,
      mediaSourceId: "source-local-lights",
      type: "movie",
      title: "Local Lights",
      description:
        "A placeholder feature used to prove native playback, resume, and watchlist behavior inside the isolated media route.",
      runtimeMinutes: 92,
      posterPath: "/media/poster-local-lights.jpg",
      releaseYear: 2026,
      rating: "PG",
      libraryStatus: "ready-for-owned-file",
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: "movie-workbench-weekend",
      accountId,
      mediaSourceId: "source-workbench-weekend",
      type: "movie",
      title: "Workbench Weekend",
      description:
        "A quiet demo movie entry for testing missing poster and missing video states without shipping media files.",
      runtimeMinutes: 78,
      posterPath: "/media/poster-workbench-weekend.jpg",
      releaseYear: 2026,
      rating: "Unrated",
      libraryStatus: "demo-placeholder",
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: "episode-signal-house-s1e1",
      accountId,
      mediaSourceId: "source-signal-house-s1e1",
      type: "episode",
      title: "Pilot Light",
      description:
        "The first placeholder episode for testing episode playback and per-profile progress.",
      runtimeMinutes: 28,
      posterPath: "/media/poster-signal-house-e1.jpg",
      releaseYear: 2026,
      rating: "TV-PG",
      libraryStatus: "ready-for-owned-file",
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: "episode-signal-house-s1e2",
      accountId,
      mediaSourceId: "source-signal-house-s1e2",
      type: "episode",
      title: "Second Signal",
      description:
        "A second placeholder episode so Continue Watching and Watchlist can cover episodic media.",
      runtimeMinutes: 31,
      posterPath: "/media/poster-signal-house-e2.jpg",
      releaseYear: 2026,
      rating: "TV-PG",
      libraryStatus: "demo-placeholder",
      createdAt: timestamp,
      updatedAt: timestamp,
    },
  ],
  genres: [
    { id: "genre-drama", accountId, name: "Drama", createdAt: timestamp, updatedAt: timestamp },
    {
      id: "genre-local-demo",
      accountId,
      name: "Local Demo",
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: "genre-local-library",
      accountId,
      name: "Local Library",
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: "genre-movie",
      accountId,
      name: "Movie",
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: "genre-documentary",
      accountId,
      name: "Documentary",
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    { id: "genre-series", accountId, name: "Series", createdAt: timestamp, updatedAt: timestamp },
  ],
  catalogItemGenres: [
    { catalogItemId: "movie-they-were-right", genreId: "genre-local-library", sortOrder: 1 },
    { catalogItemId: "movie-they-were-right", genreId: "genre-movie", sortOrder: 2 },
    { catalogItemId: "movie-survivors-of-saturn", genreId: "genre-local-library", sortOrder: 1 },
    { catalogItemId: "movie-survivors-of-saturn", genreId: "genre-movie", sortOrder: 2 },
    { catalogItemId: "movie-kabbalah-intro", genreId: "genre-local-library", sortOrder: 1 },
    { catalogItemId: "movie-kabbalah-intro", genreId: "genre-movie", sortOrder: 2 },
    { catalogItemId: "movie-jesus-was-not-a-christian", genreId: "genre-local-library", sortOrder: 1 },
    { catalogItemId: "movie-jesus-was-not-a-christian", genreId: "genre-movie", sortOrder: 2 },
    { catalogItemId: "movie-local-lights", genreId: "genre-drama", sortOrder: 1 },
    { catalogItemId: "movie-local-lights", genreId: "genre-local-demo", sortOrder: 2 },
    { catalogItemId: "movie-workbench-weekend", genreId: "genre-documentary", sortOrder: 1 },
    { catalogItemId: "movie-workbench-weekend", genreId: "genre-local-demo", sortOrder: 2 },
    { catalogItemId: "episode-signal-house-s1e1", genreId: "genre-series", sortOrder: 1 },
    { catalogItemId: "episode-signal-house-s1e1", genreId: "genre-local-demo", sortOrder: 2 },
    { catalogItemId: "episode-signal-house-s1e2", genreId: "genre-series", sortOrder: 1 },
    { catalogItemId: "episode-signal-house-s1e2", genreId: "genre-local-demo", sortOrder: 2 },
  ],
  shows: [
    {
      id: "show-signal-house",
      accountId,
      title: "Signal House",
      description:
        "A starter show with local placeholder episodes for proving show, season, and episode relationships.",
      posterPath: "/media/poster-signal-house.jpg",
      createdAt: timestamp,
      updatedAt: timestamp,
    },
  ],
  seasons: [
    {
      id: "signal-house-season-1",
      showId: "show-signal-house",
      seasonNumber: 1,
      title: "Season 1",
      createdAt: timestamp,
      updatedAt: timestamp,
    },
  ],
  episodePlacements: [
    {
      catalogItemId: "episode-signal-house-s1e1",
      showId: "show-signal-house",
      seasonId: "signal-house-season-1",
      episodeNumber: 1,
    },
    {
      catalogItemId: "episode-signal-house-s1e2",
      showId: "show-signal-house",
      seasonId: "signal-house-season-1",
      episodeNumber: 2,
    },
  ],
  watchlistEntries: [
    {
      profileId: "britton",
      catalogItemId: "movie-local-lights",
      createdAt: timestamp,
    },
  ],
  playbackProgress: [
    {
      profileId: "britton",
      catalogItemId: "movie-local-lights",
      seconds: 65,
      updatedAt: timestamp,
    },
  ],
  curationChecks: [
    {
      profileId: "britton",
      catalogItemId: "movie-local-lights",
      authorizedFileConfirmed: true,
      updatedAt: timestamp,
    },
  ],
  playbackAcceptance: [
    {
      profileId: "britton",
      catalogItemId: "movie-local-lights",
      sourceReadyConfirmed: true,
      refreshProgressConfirmed: true,
      profileIsolationConfirmed: true,
      updatedAt: timestamp,
    },
  ],
};
