export type SpiritFlixManualTagScope = "model" | "video";

export const SPIRITFLIX_MODEL_ATTRIBUTE_TAGS = new Set([
  "african",
  "arab",
  "asian",
  "bbw",
  "big ass",
  "big boobs",
  "big breast",
  "big breasts",
  "big tits",
  "black hair",
  "blonde",
  "brazilian",
  "brunette",
  "busty",
  "caucasian",
  "chinese",
  "curvy",
  "desi",
  "east asian",
  "ebony",
  "european",
  "filipina",
  "filipino",
  "eyes",
  "fit",
  "goth",
  "hispanic",
  "indian",
  "indigenous",
  "iranian",
  "japanese",
  "korean",
  "latina",
  "latino",
  "malaysian",
  "mexican",
  "middle eastern",
  "milf",
  "mixed",
  "native",
  "natural tits",
  "paki",
  "pakistani",
  "persian",
  "petite",
  "polynesian",
  "redhead",
  "south asian",
  "southeast asian",
  "skinny",
  "small tits",
  "tattooed",
  "thai",
  "thick",
  "turkish",
  "vietnamese",
  "white",
]);

const VIDEO_LEVEL_TAG_WORDS = new Set([
  "2 girls",
  "anal",
  "asmr",
  "backshot",
  "bj",
  "blowjob",
  "car",
  "compilation",
  "creampie",
  "cumshot",
  "cum on tits",
  "dance",
  "deep throat",
  "deepthroat",
  "dp",
  "facial",
  "feet",
  "fingering",
  "foot",
  "footjob",
  "footsie",
  "handjob",
  "hijab",
  "interview",
  "pov",
  "public",
  "sex",
  "solo",
  "squirt",
  "squirting",
  "threesome",
  "titjob",
  "vr",
  "wet noises",
]);

const MODEL_LEVEL_TAG_WORDS = new Set([
  "african",
  "arab",
  "ass",
  "asian",
  "bbw",
  "big",
  "black",
  "blonde",
  "boobs",
  "brazilian",
  "breast",
  "breasts",
  "brunette",
  "busty",
  "caucasian",
  "chinese",
  "curvy",
  "desi",
  "east",
  "ebony",
  "european",
  "filipina",
  "filipino",
  "eyes",
  "fit",
  "goth",
  "hair",
  "hispanic",
  "indian",
  "indigenous",
  "iranian",
  "japanese",
  "korean",
  "latina",
  "latino",
  "malaysian",
  "mexican",
  "milf",
  "middle",
  "mixed",
  "native",
  "natural",
  "paki",
  "pakistani",
  "persian",
  "petite",
  "polynesian",
  "redhead",
  "south",
  "southeast",
  "skinny",
  "small",
  "tattooed",
  "thai",
  "thick",
  "tits",
  "turkish",
  "vietnamese",
  "white",
]);

export function canonicalizeSpiritFlixManualTag(input: unknown): string {
  if (typeof input !== "string") return "";
  return input.trim().replace(/\s+/g, " ").toLowerCase();
}

export function getSpiritFlixManualTagScope(input: unknown): SpiritFlixManualTagScope {
  const tag = canonicalizeSpiritFlixManualTag(input);
  if (!tag) return "video";
  if (VIDEO_LEVEL_TAG_WORDS.has(tag)) return "video";
  if (SPIRITFLIX_MODEL_ATTRIBUTE_TAGS.has(tag)) return "model";
  const words = tag.split(/\s+/).filter(Boolean);
  if (words.some((word) => VIDEO_LEVEL_TAG_WORDS.has(word))) return "video";
  if (words.length > 0 && words.every((word) => MODEL_LEVEL_TAG_WORDS.has(word))) return "model";
  return "video";
}
